AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple Hello World Serverless project

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./testlambda.zip
      Runtime: python2.7
      Handler: testlambda.Handle
      MemorySize: 256
      Environment:
        Variables:
          LD_LIBRARY_PATH: "/var/task/lib:/lib64:/usr/lib64:/var/task"
          MYVAR: SOMEVALUE
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: any